version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: "quarterly"
  open-pull-requests-limit: 10

- package-ecosystem: "github-actions" # See documentation for possible values
  directory: "/" # Location of package manifests
  schedule:
    interval: "quarterly"
